site_name: HydroDL Docs
site_url: https://mhpi.github.io
site_author: Tadd Bindas
site_description: >-
  Documentation for hydroDL

# Repository
repo_url: https://www.github.com/mhpi/hydroDL
repo_name: mhpi/hydroDL
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
      # - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: black
      accent: indigo

plugins:
    - search    
        #plugins:
        # - social
extra:
    social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mhpi

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - toc:
        permalink: true
        title: On this page
nav:
    - HydroDL: index.md
    - Getting started: 
        - Installation: Installation.md
        - Quick Start: Quick_start.md
        - Example: Example.md
        - Contribute: Contribute.md
    - Docs: 
        - Docs.md
    - Projects: 
        - Projects.md
      

