site_name: HydroDL Docs
site_url: https://mhpi.github.io
site_author: Tadd Bindas
site_description: >-
  Documentation for hydroDL

# Repository
repo_url: https://www.github.com/mhpi/hydroDL
repo_name: mhpi/hydroDL
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
    repo: fontawesome/brands/github
  name: material
    #custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
      # - toc.integrate
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: black
      accent: indigo

plugins:
  # - blog
    - git-authors
    - git-revision-date-localized:
          enable_creation_date: true
          fallback_to_build_date: true
      # - rss:
      #      match_path: blog/posts/.*
      #     date_from_meta:
      #       as_creation: date
      #    categories:
      #      - categories
              #       - tags
   #- social:
      #cards_layout: deafult/accent
    - search:
          separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])' 
            #- minify:
            #minify_html: true
    # CI=1 mkdocs build
    #   - group:
    #         enabled: !ENV CI
    #        plugins:
    #            - git-revision-date-localized
    #            - git-committers

    # INSIDERS=1 mkdocs build
    - group:
          enabled: !ENV INSIDERS
          plugins:
              - optimize
              - privacy
extra:
    social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mhpi

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
          generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - md_in_html
    - toc:
         permalink: true
         title: On this page
    - pymdownx.emoji:
         emoji_index: !!python/name:material.extensions.emoji.twemoji
         emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true

nav:
    - HydroDL: index.md
    - Getting started: 
        - Installation: Installation.md
        - Quick Start: Quick_start.md
        - Example: Example.md
          #   - Contribute: Contribute.md
          # - Docs: 
          # - docs/index.md
          # - Datasets: docs/datasets.md  
          #  - Neural Networks: docs/neural_networks.md
          #  - Physics Models: docs/physics_models.md
          # - Experiments: docs/experiments.md
          #  - Plugins:
          #      - docs/plugins/index.md
          #      - HydroDL: docs/plugins/hydrodl.md
    - Projects: 
        - projects/index.md
        - HBV: projects/feng_2023.md
        - Muskingum-Cunge: projects/bindas_2023.md

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
